version: "3.9"

services:
  mysql:
    build:
      context: ./Database
    image: kdilipkumar/todosummary-database:27
    container_name: todo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_DATABASE: todo_db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./Backend/todo-summary-assistant
    image: kdilipkumar/todosummary-backend:27
    container_name: todo-backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/todo_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
      COHERE_API_KEY: ${COHERE_API_KEY}
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}
    ports:
      - "8080:8080"

  frontend:
    build: ./Frontend/todo
    image: kdilipkumar/todosummary-frontend:27
    container_name: todo-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  mysql_data: